### PR TITLE
feat: add chain info on other routes

### PR DESCRIPTION
**Pull request by daisai3**
- /flashloan
- /vaults
- /vaults/manage_position
- /vaults/new_position
- /swap

### CODE REVIEW

**Comment by Sen-Com** [comment]
vaults/new_position isn't working for juno
Screenshot from 2022-12-16 17-08-19

**Comment by daisai3** [comment]
> vaults/new_position isn't working for juno Screenshot from 2022-12-16 17-08-19

@Sen-Com  the issue has been fixed.

**Comment by Sen-Com** [comment]
Found another issue:
1. https://deploy-preview-138--exquisite-salamander-a1fe5e.netlify.app/juno/vaults/new_position?vault=JUNO
2. Switch to Terra network
3. URL is now: https://deploy-preview-138--exquisite-salamander-a1fe5e.netlify.app/terra/vaults/new_position?vault=JUNO which is obviously wrong and shows an empty card to the user. 

Fix: Redirect to .../terra/vaults/

**Comment by daisai3** [comment]
> Found another issue:
> 
> 1. https://deploy-preview-138--exquisite-salamander-a1fe5e.netlify.app/juno/vaults/new_position?vault=JUNO
> 2. Switch to Terra network
> 3. URL is now: https://deploy-preview-138--exquisite-salamander-a1fe5e.netlify.app/terra/vaults/new_position?vault=JUNO which is obviously wrong and shows an empty card to the user.
> 
> Fix: Redirect to .../terra/vaults/

@Sen-Com  this issue has been fixed.

**Pull request closed without merging**
