### PR TITLE
Feat/comdex integration

### PR DESCRIPTION
**Pull request by 0xFable**
## Description and Motivation

Integrates the WhiteWhale Liquidity Hubs deployed on the Comdex chain into the Migaloo-frontend. 
Users can now select the chain `Comdex` on mainnet or testnet 

On mainnet there are 2 pools, 1 vault. CMDX-ATOM, CMDX-CMST and CMST.
On testnet there are 2 pools, 2 vaults; tbd

## Checklist:

- [ ] I have read [Migaloo's contribution guidelines](https://github.com/White-Whale-Defi-Platform/migaloo-frontend/blob/main/CONTRIBUTING.md).
- [ ] My pull request has a sound title and description (not something vague like `Update index.md`)
- [ ] All existing and new tests are passing.
- [ ] I updated/added relevant documentation.
- [ ] The code is formatted properly `yarn lint`.
- [ ] The project builds and is able to deploy on Netlify `yarn build`.

Testing

Testing: 
- [X] Swaps
- [X] Provide Liquidity
- [X] Vault deposit+withdraw

### CODE REVIEW

**Review by kerber0x — CHANGES_REQUESTED** [review]
The comdex network logo is broken:

Screenshot from 2023-01-04 16-21-37

The CMST logo is not USDT, it is something else: 

Screenshot from 2023-01-04 16-22-12


Screenshot from 2023-01-04 16-23-56

https://app.cswap.one/farm/2 You can grab it from here.

**Comment by kerber0x** [comment]
Screenshot from 2023-01-04 16-26-39

We don't have a USDT vault on comdex, it is CMST @0xFable

**Review by kerber0x — DISMISSED** [review]
:star2: great job!

**Review by daisai3 — APPROVED** [review]
@0xFable  LGTM!

**Review by daisai3 — APPROVED** [review]
@0xFable LGTM!

**Pull request merged**
